server:
  port: 8080

spring:
  application:
    name: getway-servier

dubbo:
  registry:
    protocol: nacos
    address: nacos://${spring.cloud.nacos.server-addr}
  protocol:
    name: dubbo
    port: -1