server:
  port: 8081

spring:
  application:
    name: usercenter
  datasource:
    url: jdbc:mysql://${gdcmcs.datasource.ip}:3306/usercenter?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${gdcmcs.datasource.username}
    password: ${gdcmcs.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  registry:
    protocol: nacos
    address: nacos://${spring.cloud.nacos.server-addr}
  protocol:
    name: dubbo
    port: -1